name: Run K6 Tests in K8s
on:
  workflow_dispatch:
    inputs:
      parallelism:
        description: 'Number of parallel k6 test instances to run'
        required: true
        type: number
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  run-k6-tests:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup kubectl
        uses: ./.github/actions/setup-kubectl
        with:
          aws-region: ${{vars.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-role
          eks-cluster-name: monocle-dev
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
      - name: Install esbuild and create bundle
        run: |
          # Install esbuild globally
          npm install -g esbuild
          # Run the build script
          cd e2e/k6/http
          chmod +x build.sh
          ./build.sh
      - name: Create namespace and ConfigMap
        run: |
          NAMESPACE="k6-test-$(date +%Y%m%d-%H%M%S)"
          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
          kubectl create namespace $NAMESPACE
          kubectl create configmap k6-test-cm --from-file=bundle.js=e2e/k6/http/dist/bundle.js -n $NAMESPACE
      - name: Run K6 Test
        run: |
          kubectl apply -f - <<EOF
          apiVersion: k6.io/v1alpha1
          kind: TestRun
          metadata:
            name: k6-test
            namespace: $NAMESPACE
          spec:
            parallelism: ${{ inputs.parallelism }}
            script:
              configMap:
                name: k6-test-cm
                file: bundle.js
          EOF
